wifi: mt76: mt7996: add missing argument in mt7996_queue_rx_skb()
An argument has been added in .rx_skb driver ops callback after
introducing WED RX support. Align it to fix the following compile error:

>> drivers/net/wireless/mediatek/mt76/mt7996/mmio.c:328:13: error: incompatible function pointer types initializing 'void (*)(struct mt76_dev *, enum mt76_rxq_id, struct sk_buff *, u32 *)' (aka 'void (*)(struct mt76_dev *, enum mt76_rxq_id, struct sk_buff *, unsigned int *)') with an expression of type 'void (struct mt76_dev *, enum mt76_rxq_id, struct sk_buff *)' [-Werror,-Wincompatible-function-pointer-types]
                   .rx_skb = mt7996_queue_rx_skb,
                             ^~~~~~~~~~~~~~~~~~~
   1 error generated.

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Shayne Chen <shayne.chen@mediatek.com>
Signed-off-by: Felix Fietkau <nbd@nbd.name>