mt76: mt7915: fix struct ieee80211_iface_limit
Fixes following compiler error:

 mt7915/init.c:47:2: error: expected expression before '}' token

Fixes: 2741fd071bb7 ("mt76: mt7915: support 32 station interfaces")
Signed-off-by: Petr Štetiar <ynezz@true.cz>